trigger:
  branches:
    include:
    - '*'
  paths:
    exclude:
    - .appveyor.yml
    - .travis.yml

pr:
  branches:
    include:
    - '*'
  paths:
    exclude:
    - .appveyor.yml
    - .travis.yml

jobs:
- job:
  pool:
    vmImage: windows-latest
  strategy:
    matrix:
      Release:
        configuration: Release
      Debug:
        configuration: Debug

  steps:
  - script: |
      git submodule update --init --recursive
      mkdir build
      cd build
      cmake .. -G "Visual Studio 16 2019" -A Win32
    displayName: 'Before build'

  - script: |
      cd build
      cmake --build . --config %configuration%
    displayName: 'Build'

  - task: CopyFiles@2
    displayName: 'Copy files to $(Build.ArtifactStagingDirectory)'
    condition: and(succeeded(), eq(variables['Agent.JobName'], 'Release'))
    inputs:
      Contents: |
          COPYING
          README.md
          build\bin\$(configuration)\Cxbx.exe
          build\bin\$(configuration)\glew32.dll
          build\bin\$(configuration)\subhook.dll
          build\bin\$(configuration)\CxbxVSBC.dll
          build\bin\$(configuration)\SDL2.dll
          build\bin\$(configuration)\cxbxr-debugger.exe
          build\bin\$(configuration)\capstone.dll
          build\bin\$(configuration)\cx_x86.dll
      TargetFolder: '$(Build.ArtifactStagingDirectory)'
      flattenFolders: true

  - publish: $(Build.ArtifactStagingDirectory)
    artifact: $(configuration)
    condition: and(succeeded(), eq(variables['Agent.JobName'], 'Release'))
    displayName: Publish artifact(s)
