init:
  - ps: Update-AppveyorBuild -Version "$env:appveyor_repo_commit"
branches:
  only:
  - master
image: 
- Visual Studio 2017  
configuration:
- Release
- Debug
build:
  project: build/win32/Cxbx.sln
  parallel: true
  verbosity: minimal
artifacts:
- path: export\Release.zip
- path: export\Debug.zip
install:
  # Git clone happens between init and install 
  - cmd: git submodule update --init --recursive