# Documentation is here: https://www.appveyor.com/docs/appveyor-yml/

init:
  - ps: Update-AppveyorBuild -Version "$env:appveyor_repo_commit"

image:
  # If this is modified, please also update the build script
  - Visual Studio 2017

configuration:
  # The builds will be run in this order
  - Release
  - Debug

build_script:
  - cmd: appveyor-build.bat %CONFIGURATION%

after_build:
  - cmd: appveyor-gather.bat %CONFIGURATION%

artifacts:
  - path: export/*.zip

install:
  # Git clone happens between init and install
  - cmd: git submodule update --init --recursive
